version: "3.7"

###############################################################################
#                                   Network                                   #
###############################################################################

networks:
  web:
  internal:
    internal: true

###############################################################################
#                                  Web zone                                   #
###############################################################################

services:
  traefik:
    image: traefik:1.7
    restart: always
    command:
      - --accesslogsfile=/etc/traefik/access.log
      - --api.dashboard
      - --docker
      - --docker.watch
      - --docker.domain=${DOMAIN}
      - --docker.exposedByDefault=false
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.httpChallenge.entryPoint=http
      - --acme.entrypoint=https
      - --acme.domains=${DOMAIN}
      - --acme.email=${ADMIN}@${DOMAIN}
      - --acme.onHostRule
      - --acme.storage=/etc/traefik/acme.json
      # - --logLevel=DEBUG
      - --sendAnonymousUsage=false
    labels:
      traefik.enable: "true"
      traefik.backend: traefik
      traefik.port: 8080
      traefik.frontend.auth.basic.users: "${ADMIN_HTPASSWD}"
      traefik.frontend.rule: Host:traefik.${DOMAIN}
    networks:
      - web
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_DIR}/traefik:/etc/traefik"

  ###############################################################################
  #                                  App                                        #
  ###############################################################################

  # # Blog
  # ghost:
  #   image: ghost:alpine
  #   restart: always
  #   env_file: .env.ghost
  #   networks:
  #     - internal
  #   volumes:
  #     - "${DATA_DIR}/ghost:/var/lib/ghost/content"
  #   labels:
  #     traefik.enable: "true"
  #     traefik.backend: ghost
  #     traefik.network: "island_web"
  #     traefik.port: 2368
  #     traefik.frontend.rule: Host:${DOMAIN},blog.${DOMAIN}

  # # Blog
  # hugo:
  #   build: hugo
  #   image: localhost/hugo
  #   command:
  #     - --baseURL=https://blog.${DOMAIN}
  #     - --appendPort=false
  #     - --bind=0.0.0.0
  #     - --buildDrafts
  #     # - --theme=bleak
  #     - --cleanDestinationDir
  #     - --gc
  #     - --verbose
  #     - server
  #   restart: always
  #   init: true
  #   networks:
  #     - internal
  #   volumes:
  #     - "${DATA_DIR}/hugo:/site"
  #   labels:
  #     traefik.enable: "true"
  #     traefik.backend: hugo
  #     traefik.network: "island_web"
  #     traefik.port: 1313
  #     traefik.frontend.rule: Host:${DOMAIN},blog.${DOMAIN}

  nextcloud:
    image: nextcloud:production
    restart: always
    networks:
      - web
      - internal
    env_file: .env.nextcloud
    volumes:
      - "${DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps"
      - "${DATA_DIR}/nextcloud/config:/var/www/html/config"
      - "${DATA_DIR}/nextcloud/data:/var/www/html/data"
    labels:
      traefik.enable: "true"
      traefik.backend: nextcloud
      traefik.network: "island_web"
      traefik.port: 80
      traefik.frontend.rule: Host:cloud.${DOMAIN}

  privatebin:
    image: privatebin/nginx-fpm-alpine
    restart: always
    init: true
    read_only: true
    networks:
      - internal
    volumes:
      - "${DATA_DIR}/privatebin:/srv/data"
    labels:
      traefik.enable: "true"
      traefik.backend: privatebin
      traefik.network: "island_internal"
      traefik.port: 80
      traefik.frontend.rule: Host:paste.${DOMAIN}

  thelounge:
    image: thelounge/thelounge:alpine
    restart: always
    init: true
    networks:
      - web
    volumes:
      - "${DATA_DIR}/thelounge:/var/opt/thelounge"
    labels:
      traefik.enable: "true"
      traefik.backend: thelounge
      traefik.network: "island_web"
      traefik.port: 9000
      traefik.frontend.rule: Host:irc.${DOMAIN}

  # riot:
  #   image: avhost/docker-matrix-riot:v1.1.2
  #   restart: always
  #   networks:
  #     - web
  #   volumes:
  #     - "${DATA_DIR}/riot:/data"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=riot"
  #     - "traefik.port=8080"
  #     - "traefik.frontend.rule=Host:riot.${DOMAIN},matrix.${DOMAIN}"

  # mailpile:
  #   build:
  #     context: "https://github.com/mailpile/mailpile"
  #   image: mailpile/mailpile:master
  #   networks:
  #     - web
  #   volumes:
  #     - "${DATA_DIR}/mailpile/data:/home/mailpile/.local/share/Mailpile"
  #     - "${DATA_DIR}/mailpile/gpg:/home/mailpile/.gnupg"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=mailpile"
  #     - "traefik.network=island_web"
  #     - "traefik.port=33411"
  #     - "traefik.frontend.rule=Host:mail.${DOMAIN},webmail.${DOMAIN}"

  # kresus:
  #   image: bnjbvr/kresus
  #   restart: always
  #   networks:
  #     - web
  #   environment:
  #     LOCAL_USER_ID: 1000
  #   volumes:
  #     - "${DATA_DIR}/kresus/data:/home/user/data"
  #     - "${DATA_DIR}/kresus/weboob:/weboob"
  #     - "${DATA_DIR}/kresus/config.ini:/opt/config.ini"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=kresus"
  #     - "traefik.network=island_web"
  #     - "traefik.port=9876"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$m2o7bef7$$WrzvSKua5Mi5EAbNO3FJH0"
  #     - "traefik.frontend.rule=Host:kresus.${DOMAIN}"

  # duplicati:
  #   image: linuxserver/duplicati
  #   networks:
  #     - web
  #   env_file: .env
  #   environment:
  #     PUID: 8426
  #     PGID: 8426
  #   volumes:
  #     - "${DATA_DIR}/duplicati/config:/config"
  #     - "${DATA_DIR}/duplicati/backups:/backups"
  #     - "${DATA_DIR}/duplicati/source:/source"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=8200"
  #     - "traefik.backend=duplicati"
  #     - "traefik.network=island_web"
  #     # - "traefik.frontend.auth.basic.users=${ADMIN}:${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.rule=Host:duplicati.${DOMAIN}"

  # softether:
  #   image: siomiz/softethervpn:openvpn
  #   networks:
  #     - web
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - target: 1194
  #       published: 1194
  #       protocol: udp
  #       mode: host
  #     - target: 5555
  #       published: 5555
  #       protocol: tcp
  #       mode: host
  #   env_file: .env.softether
  #   volumes:
  #      - "${DATA_DIR}/softether/vpn_server.config:/opt/vpn_server.config"
  #   labels:
  #     - "traefik.enable=false"
  #     - "traefik.port=443"
  #     - "traefik.backend=softether"
  #     - "traefik.network=island_web"
  #     - "traefik.frontend.rule=Host:vpn.${DOMAIN},softether.${DOMAIN}"

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    restart: always
    init: true
    networks:
      - web
    ports:
      - "110:8388"
      - "8009:8388"
      - "8080:8388"
    env_file: .env.shadowsocks

  torrent:
    image: boypt/cloud-torrent # simple-torrent fork
    restart: always
    init: true
    networks:
      - web
    env_file: .env.torrent
    volumes:
      - "${DATA_DIR}/torrents:/downloads"
    labels:
      traefik.enable: "true"
      traefik.backend: torrents
      traefik.network: island_web
      traefik.port: 3000
      traefik.frontend.rule: Host:torrents.${DOMAIN}

  # Youtube-DL
  # ytdl:
  #   image: kmb32123/youtube-dl-server:alpine
  #   restart: always
  #   networks:
  #     - web
  #   volumes:
  #     - "${DATA_DIR}/nextcloud/data/remy/files/Téléchargements/YoutubeDL:/youtube-dl"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=ytdl"
  #     - "traefik.network=island_web"
  #     - "traefik.port=8080"
  #     - "traefik.frontend.rule=Host:ytdl.${DOMAIN}"
  #     - "traefik.frontend.auth.basic.users=${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.redirect.regex=^https?://([^/]*)/?$$"
  #     - "traefik.frontend.redirect.replacement=https://$$1/youtube-dl"
  #     - "traefik.frontend.redirect.permanent=true"

  # # Manage photos
  # photoprism:
  #   image: photoprism/photoprism
  #   restart: always
  #   networks:
  #     - web
  #     - internal
  #   env_file: .env.photoprism
  #   volumes:
  #     - "${DATA_DIR}/photoprism:/Photos"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=photoprism"
  #     - "traefik.network=island_web"
  #     - "traefik.port=80"
  #     - "traefik.frontend.rule=Host:photoprism.${DOMAIN}"
  #     - "traefik.frontend.auth.basic.users=${ADMIN_HTPASSWD}"

  # Music download manager
  headphones:
    image: linuxserver/headphones
    restart: always
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${DATA_DIR}/headphones/config:/config
      - ${DATA_DIR}/headphones/downloads:/downloads
      - ${DATA_DIR}/headphones/music:/music
    labels:
      traefik.enable: true
      traefik.backend: headphones
      traefik.network: island_web
      traefik.port: 8181
      traefik.frontend.rule: Host:headphones.${DOMAIN}
      # traefik.frontend.auth.basic.users: ${ADMIN_HTPASSWD}

  # eBooks manager
  cops:
    image: linuxserver/cops
    restart: always
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${DATA_DIR}/cops/config:/config
      - ${DATA_DIR}/cops/books:/books
    labels:
      traefik.enable: true
      traefik.backend: cops
      traefik.network: island_web
      traefik.port: 80
      traefik.frontend.rule: Host:cops.${DOMAIN},ebooks.${DOMAIN}
      # traefik.frontend.auth.basic.users: ${ADMIN_HTPASSWD}

  # Download manager
  pyload:
    image: linuxserver/pyload
    restart: always
    init: true
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${DATA_DIR}/pyload/config:/config
      - ${DATA_DIR}/pyload/downloads:/downloads
    labels:
      traefik.enable: true
      traefik.backend: pyload
      traefik.network: island_web
      traefik.port: 8000
      traefik.frontend.rule: Host:dl.${DOMAIN},pyload.${DOMAIN}
      # traefik.frontend.auth.basic.users: ${ADMIN_HTPASSWD}

  ###############################################################################
  #                               Internal zone                                 #
  ###############################################################################

  # mariadb:
  #   image: mariadb:10
  #   env_file: .env
  #   networks:
  #     - internal
  #   volumes:
  #     - "${DATA_DIR}/mariadb/data:/var/lib/mysql"
  #     - "${DATA_DIR}/island/scripts/photoprism.sql:/docker-entrypoint-initdb.d/photoprism.sql"
  #   labels:
  #     - "traefik.enable=false"

  postgres:
    image: postgres:11-alpine
    restart: always
    env_file: .env
    # command:
    #   - postgres
    #   - -c 'max_connections=200'
    #   - -c 'shared_buffers=1GB'
    #   - -c 'effective_cache_size=3GB'
    #   - -c 'work_mem=5242kB'
    #   - -c 'maintenance_work_mem=256MB'
    #   - -c 'min_wal_size=1GB'
    #   - -c 'max_wal_size=2GB'
    #   - -c 'checkpoint_completion_target=0.7'
    #   - -c 'wal_buffers=16MB'
    #   - -c 'default_statistics_target=100'
    #   - -c 'random_page_cost=4'
    networks:
      - internal
    volumes:
      - "./scripts/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql"
      - "${DATA_DIR}/postgres/data:/var/lib/postgresql/data"
    labels:
      traefik.enable: "false"

  # Cache
  redis:
    image: redis:alpine
    restart: always
    init: true
    networks:
      - internal
    sysctls:
      - net.core.somaxconn=4096
      # - vm.overcommit_memory=1
    volumes:
      - "${DATA_DIR}/redis:/data"
    labels:
      traefik.enable: "false"

  # # Elastic Search
  # # https://www.docker.elastic.co/
  # elasticsearch:
  #   build: build/elasticsearch
  #   image: localhost/elasticsearch-oss
  #   init: true
  #   networks:
  #     - internal
  #   env_file: .env.elasticsearch
  #   # sysctls:
  #   #   - vm.max_map_count=262144 # bug OCI runtime create failed: sysctl "vm.max_map_count" is not in a separate kernel namespace: unknown https://github.com/moby/moby/issues/30778
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
  #   labels:
  #     traefik.enable: "false"

  # # Monitoring
  # cadvisor:
  #   image: google/cadvisor
  #   restart: always
  #   networks:
  #     - internal
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=8080"
  #     - "traefik.backend=cadvisor"
  #     - "traefik.network=island_internal"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$ot35v8Up$$0yTQ2LLJqsmPT5SE5W6MF/"
  #     - "traefik.frontend.rule=Host:cadvisor.${DOMAIN}"

  # # Monitoring
  # glances:
  #   image: nicolargo/glances:latest-alpine
  #   restart: always
  #   pid: host
  #   networks:
  #     - internal
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   environment:
  #     - "GLANCES_OPT=-w"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=61208"
  #     - "traefik.backend=glances"
  #     - "traefik.network=island_internal"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$O0LDFg8Y$$d3vfb28aMKIjdHi26MJ0g0"
  #     - "traefik.frontend.rule=Host:glances.${DOMAIN}"

  # Monitoring
  netdata:
    image: netdata/netdata
    restart: always
    init: true
    hostname: ${DOMAIN}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    labels:
      traefik.enable: true
      traefik.port: 19999
      traefik.backend: netdata
      traefik.network: island_internal"
      traefik.frontend.rule: Host:netdata.${DOMAIN},monitoring.${DOMAIN}
      # traefik.frontend.auth.basic.users: ${ADMIN}:$$apr1$$O0LDFg8Y$$d3vfb28aMKIjdHi26MJ0g0"
  # # Backup
  # restic:
  #   image: lobaro/restic-backup-docker
  #   restart: always
  #   networks:
  #     - web
  #   volumes:
  #     - "${DATA_DIR}/traefik:/data/traefik"
  #   env_file:
  #     - .env.restic
  #   labels:
  #     - "traefik.enable=false"
