version: '3.4'

###############################################################################
#                                   Network                                   #
###############################################################################

networks:
  web:
  internal:
    internal: true

###############################################################################
#                                  Web zone                                   #
###############################################################################

services:
  traefik:
    image: traefik:alpine
    restart: always
    command:
      - --accesslogsfile=/etc/traefik/access.log
      - --api.dashboard # Replace --web
      - --docker
      - --docker.watch
      - --docker.domain=${DOMAIN}
      - --docker.exposedByDefault=false
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.httpChallenge.entryPoint=http
      - --acme.entrypoint=https
      - --acme.domains=${DOMAIN}
      - --acme.email=${ADMIN}@${DOMAIN}
      - --acme.onHostRule
      - --acme.storage=/etc/traefik/acme/acme.json
      # - --logLevel=DEBUG
      - --sendAnonymousUsage=false 
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$acldxzHL$$aIE2PcUEFioj4PyUvBw/Q."
      - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
    networks:
      - web
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dev/null:/traefik.toml"
      - "${DATA_DIR}/traefik:/etc/traefik"

###############################################################################
#                                  App                                        #
###############################################################################

  # Blog
  ghost:
    image: ghost:alpine
    restart: always
    env_file: .env.ghost
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/ghost:/var/lib/ghost/content"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ghost"
      - "traefik.network=island_web"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:${DOMAIN},blog.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  # Blog
  hugo:
    build: hugo
    image: localhost/hugo
    command: 
      - --baseURL=https://hugo.${DOMAIN}
      - --appendPort=false
      - --bind=0.0.0.0
      - --buildDrafts
      - --theme=bleak
      - --cleanDestinationDir
      - --gc
      - --verbose
      - server
    restart: always
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/hugo:/site"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hugo"
      - "traefik.network=island_web"
      - "traefik.port=1313"
      # - "traefik.frontend.rule=Host:${DOMAIN},blog.${DOMAIN}"
      - "traefik.frontend.rule=Host:hugo.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  nextcloud:
    image: nextcloud:15
    restart: always
    networks:
      - internal
    env_file: .env.nextcloud
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps"
      - "${DATA_DIR}/nextcloud/config:/var/www/html/config"
      - "${DATA_DIR}/nextcloud/data:/var/www/html/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.network=island_web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:cloud.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  thelounge:
    image: thelounge/lounge:alpine
    restart: always
    networks:
      - web
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/thelounge:/home/lounge/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=thelounge"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:irc.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  riot:
    image: silviof/matrix-riot-docker
    restart: always
    networks:
      - web
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/riot:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=riot"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:riot.${DOMAIN},matrix.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  # mailpile:
  #   build: 
  #     context: "https://github.com/mailpile/mailpile"
  #   image: mailpile/mailpile:master
  #   networks:
  #     - web
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/mailpile/data:/home/mailpile/.local/share/Mailpile"
  #     - "${DATA_DIR}/mailpile/gpg:/home/mailpile/.gnupg"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=mailpile"
  #     - "traefik.network=island_web"
  #     - "traefik.port=33411"
  #     - "traefik.frontend.rule=Host:mail.${DOMAIN},webmail.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  kresus:
    image: bnjbvr/kresus
    restart: always
    networks:
      - web
    environment:
      LOCAL_USER_ID: 1000
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/kresus/data:/home/user/data"
      - "${DATA_DIR}/kresus/weboob:/weboob"
      - "${DATA_DIR}/kresus/config.ini:/opt/config.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kresus"
      - "traefik.network=island_web"
      - "traefik.port=9876"
      - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$m2o7bef7$$WrzvSKua5Mi5EAbNO3FJH0"
      - "traefik.frontend.rule=Host:kresus.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  # duplicati:
  #   image: linuxserver/duplicati
  #   networks:
  #     - web
  #   env_file: .env
  #   environment:
  #     PUID: 8426
  #     PGID: 8426
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/duplicati/config:/config"
  #     - "${DATA_DIR}/duplicati/backups:/backups"
  #     - "${DATA_DIR}/duplicati/source:/source"
  #   labels: 
  #     - "traefik.enable=true"
  #     - "traefik.port=8200"
  #     - "traefik.backend=duplicati"
  #     - "traefik.network=island_web"
  #     # - "traefik.frontend.auth.basic.users=${ADMIN}:${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.rule=Host:duplicati.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  # softether:
  #   image: siomiz/softethervpn:openvpn
  #   networks:
  #     - web
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - target: 1194
  #       published: 1194
  #       protocol: udp
  #       mode: host
  #     - target: 5555
  #       published: 5555
  #       protocol: tcp
  #       mode: host
  #   env_file: .env.softether
  #   volumes: 
  #      - "/etc/localtime:/etc/localtime:ro"
  #      - "${DATA_DIR}/softether/vpn_server.config:/opt/vpn_server.config"
  #   labels:
  #     - "traefik.enable=false"
  #     - "traefik.port=443"
  #     - "traefik.backend=softether"
  #     - "traefik.network=island_web"
  #     - "traefik.frontend.rule=Host:vpn.${DOMAIN},softether.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    restart: always
    ports:
      - "110:8388"
      - "8009:8388"
      - "8080:8388"
    env_file: .env.shadowsocks

  cloudtorrent:
    image: jpillora/cloud-torrent
    restart: always
    networks:
      - web
    env_file: .env.cloudtorrent
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/nextcloud/data/remy/files/Téléchargements/Torrents:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cloudtorrent"
      - "traefik.network=island_web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:torrents.${DOMAIN}"
      # - "traefik.frontend.auth.basic.usersFile=.htpasswd.cloudtorrent"
      - "traefik.frontend.auth.basic.users=francois:$$apr1$$y1yJtAIV$$v9DVYcVX..ZXLehoOMsVk1,remy:$$apr1$$iiR/Mbdg$$e0c4Bjpuw5lwCpi4KA2nO0"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
    
  ytdl:
    image: kmb32123/youtube-dl-server:alpine
    restart: always
    networks:
      - web
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/nextcloud/data/remy/files/Téléchargements/YoutubeDL:/youtube-dl"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ytdl"
      - "traefik.network=island_web"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ytdl.${DOMAIN}"
      - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$/4j3KEN2$$qwzvGtfJC2N5dAZI1suls/"
      - "traefik.frontend.redirect.regex=^https?://([^/]*)/?$$"
      - "traefik.frontend.redirect.replacement=https://$$1/youtube-dl"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
    
  # photoprism:
  #   image: photoprism/photoprism
  #   restart: always
  #   networks:
  #     - web
  #     - internal
  #   env_file: .env.photoprism
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/photoprism:/Photos"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=photoprism"
  #     - "traefik.network=island_web"
  #     - "traefik.port=80"
  #     - "traefik.frontend.rule=Host:photoprism.${DOMAIN}"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$esnLsoyU$$3VtNqW13haYzEzcpnubYJ1"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

###############################################################################
#                               Internal zone                                 #
###############################################################################

  # mariadb:
  #   image: mariadb:10
  #   env_file: .env
  #   networks:
  #     - internal
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/mariadb/data:/var/lib/mysql"
  #     - "${DATA_DIR}/island/scripts/photoprism.sql:/docker-entrypoint-initdb.d/photoprism.sql"
  #   labels:
  #     - "traefik.enable=false"

  postgres:
    image: postgres:10-alpine
    restart: always
    env_file: .env
    # command:
    #   - postgres
    #   - -c 'max_connections=200'
    #   - -c 'shared_buffers=1GB'
    #   - -c 'effective_cache_size=3GB'
    #   - -c 'work_mem=5242kB'
    #   - -c 'maintenance_work_mem=256MB'
    #   - -c 'min_wal_size=1GB'
    #   - -c 'max_wal_size=2GB'
    #   - -c 'checkpoint_completion_target=0.7'
    #   - -c 'wal_buffers=16MB'
    #   - -c 'default_statistics_target=100'
    #   - -c 'random_page_cost=4'
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/postgres/data:/var/lib/postgresql/data"
      - "${DATA_DIR}/island/scripts/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql"
      - "${DATA_DIR}/island/scripts/photoprism.sql:/docker-entrypoint-initdb.d/photoprism.sql"
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
    sysctls:
      - net.core.somaxconn=4096
      # - vm.overcommit_memory=1
    volumes:
      - "${DATA_DIR}/redis:/data"
    labels:
      - "traefik.enable=false"

  # https://www.docker.elastic.co/
  elasticsearch:
    build: elasticsearch
    image: localhost/elasticsearch-oss
    networks:
      - internal
    env_file: .env.elasticsearch
    # sysctls:
    #   - vm.max_map_count=262144 # bug OCI runtime create failed: sysctl "vm.max_map_count" is not in a separate kernel namespace: unknown https://github.com/moby/moby/issues/30778
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
    labels:
      - "traefik.enable=false"

  # solr:
  #   image: solr:7-slim
  #   networks:
  #     - internal
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/solr:/opt/solr/server/solr/mycores"
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - nextant
  #   labels:
  #     - "traefik.enable=false"

  # Database management
  # adminer:
  #   image: adminer
  #   networks:
  #     - internal
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=8080"
  #     - "traefik.backend=adminer"
  #     - "traefik.network=island_internal"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.rule=Host:adminer.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  # Monitoring 
  # cadvisor:
  #   image: google/cadvisor
  #   restart: always
  #   networks:
  #     - internal
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=8080"
  #     - "traefik.backend=cadvisor"
  #     - "traefik.network=island_internal"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$ot35v8Up$$0yTQ2LLJqsmPT5SE5W6MF/"
  #     - "traefik.frontend.rule=Host:cadvisor.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  # Monitoring 
  # netdata:
  #   image: titpetric/netdata
  #   restart: always
  #   networks:
  #     - internal
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=19999"
  #     - "traefik.backend=netdata"
  #     - "traefik.network=island_internal"
  #     - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$6KCb.oNU$$FOG89Lv5PReyNPcL3cCdD1"
  #     - "traefik.frontend.rule=Host:netdata.${DOMAIN}"
  #     - "traefik.frontend.headers.customFrameOptionsValue=DENY"
  #     - "traefik.frontend.headers.contentTypeNosniff=true"
  #     - "traefik.frontend.headers.browserXSSFilter=true"

  # Monitoring
  glances:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "GLANCES_OPT=-w"
    labels:
      - "traefik.enable=true"
      - "traefik.port=61208"
      - "traefik.backend=glances"
      - "traefik.network=island_internal"
      - "traefik.frontend.auth.basic.users=${ADMIN}:$$apr1$$O0LDFg8Y$$d3vfb28aMKIjdHi26MJ0g0"
      - "traefik.frontend.rule=Host:glances.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  # Backup
  # restic:
  #   image: lobaro/restic-backup-docker
  #   restart: always
  #   networks:
  #     - web
  #   volumes:
  #     - "${DATA_DIR}/traefik:/data/traefik"
  #   env_file:
  #     - .env.restic
  #   labels:
  #     - "traefik.enable=false"

    
