version: '3.4'

###############################################################################
#                                   Network                                   #
###############################################################################

networks:
  web:
  internal:
    internal: true

###############################################################################
#                                  Web zone                                   #
###############################################################################

services:
  traefik:
    image: traefik:alpine
    restart: always
    command:
      - --accesslogsfile=/etc/traefik/access.log
      - --api.dashboard # Replace --web
      - --docker
      - --docker.watch
      - --docker.domain=${DOMAIN}
      - --docker.exposedByDefault=false
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.httpChallenge.entryPoint=http
      - --acme.entrypoint=https
      - --acme.domains=${DOMAIN}
      - --acme.email=${ADMIN}@${DOMAIN}
      - --acme.onHostRule
      - --acme.storage=/etc/traefik/acme/acme.json
      # - --logLevel=DEBUG
      - --sendAnonymousUsage=false 
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=${ADMIN}:$$apr1$$acldxzHL$$aIE2PcUEFioj4PyUvBw/Q."
      - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
    networks:
      - web
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dev/null:/traefik.toml"
      - "${DATA_DIR}/traefik:/etc/traefik"

###############################################################################
#                                  App                                        #
###############################################################################

  ghost:
    image: ghost:alpine
    restart: always
    env_file: .env.ghost
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/ghost:/var/lib/ghost/content"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ghost"
      - "traefik.network=island_web"
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:${DOMAIN},blog.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  nextcloud:
    # build: nextcloud
    # image: localhost/nextcloud:latest
    image: nextcloud:13
    restart: always
    networks:
      - internal
    env_file: .env.nextcloud
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps"
      - "${DATA_DIR}/nextcloud/config:/var/www/html/config"
      - "${DATA_DIR}/nextcloud/data:/var/www/html/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.network=island_web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:cloud.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  thelounge:
    image: thelounge/lounge:alpine
    restart: always
    networks:
      - web
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/thelounge:/home/lounge/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=thelounge"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:irc.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  # mailpile:
  #   build: 
  #     context: "https://github.com/mailpile/mailpile"
  #   image: mailpile/mailpile:master
  #   networks:
  #     - web
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/mailpile/data:/home/mailpile/.local/share/Mailpile"
  #     - "${DATA_DIR}/mailpile/gpg:/home/mailpile/.gnupg"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=mailpile"
  #     - "traefik.network=island_web"
  #     - "traefik.port=33411"
  #     - "traefik.frontend.rule=Host:mail.${DOMAIN},webmail.${DOMAIN}"

  kresus:
    image: bnjbvr/kresus
    restart: always
    networks:
      - web
    environment:
      LOCAL_USER_ID: 1000
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/kresus/data:/home/user/data"
      - "${DATA_DIR}/kresus/weboob:/weboob"
      - "${DATA_DIR}/kresus/config.ini:/opt/config.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kresus"
      - "traefik.network=island_web"
      - "traefik.port=9876"
      - "traefik.frontend.auth.basic=${ADMIN}:$$apr1$$m2o7bef7$$WrzvSKua5Mi5EAbNO3FJH0"
      - "traefik.frontend.rule=Host:kresus.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"

  # duplicati:
  #   image: linuxserver/duplicati
  #   networks:
  #     - web
  #   env_file: .env
  #   environment:
  #     PUID: 8426
  #     PGID: 8426
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/duplicati/config:/config"
  #     - "${DATA_DIR}/duplicati/backups:/backups"
  #     - "${DATA_DIR}/duplicati/source:/source"
  #   labels: 
  #     - "traefik.enable=true"
  #     - "traefik.port=8200"
  #     - "traefik.backend=duplicati"
  #     - "traefik.network=web"
  #     # - "traefik.frontend.auth.basic=${ADMIN}:${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.rule=Host:duplicati.${DOMAIN}"

  # softether:
  #   image: siomiz/softethervpn:openvpn
  #   networks:
  #     - web
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - target: 1194
  #       published: 1194
  #       protocol: udp
  #       mode: host
  #     - target: 5555
  #       published: 5555
  #       protocol: tcp
  #       mode: host
  #   env_file: .env.softether
  #   volumes: 
  #      - "/etc/localtime:/etc/localtime:ro"
  #      - "${DATA_DIR}/softether/vpn_server.config:/opt/vpn_server.config"
  #   labels:
  #     - "traefik.enable=false"
  #     - "traefik.port=443"
  #     - "traefik.backend=softether"
  #     - "traefik.network=web"
  #     - "traefik.frontend.rule=Host:vpn.${DOMAIN},softether.${DOMAIN}"

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    restart: always
    ports:
      - "110:8388"
      - "8009:8388"
      - "8080:8388"
    env_file: .env.shadowsocks


  torrent:
    image: jpillora/cloud-torrent
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/torrent:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=torrent"
      - "traefik.network=island_web"
      - "traefik.port=3000"
      - "traefik.frontend.auth.basic=${ADMIN}:$$apr1$$Mb/FETq.$$uAImZtJ9kd8ISF3deDypL0"
      - "traefik.frontend.rule=Host:torrent.${DOMAIN}"
      - "traefik.frontend.headers.customFrameOptionsValue=DENY"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
    


###############################################################################
#                               Internal zone                                 #
###############################################################################

  # mariadb:
  #   image: mariadb
  #   env_file: .env
  #   networks:
  #     - backend
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/mariadb/data:/var/lib/mysql"
  #     # - "${DATA_DIR}/island/scripts/database.sql:/docker-entrypoint-initdb.d/database.sql"
  #   labels:
  #     - "traefik.enable=false"

  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    # command:
    #   - postgres
    #   - -c 'max_connections=200'
    #   - -c 'shared_buffers=1GB'
    #   - -c 'effective_cache_size=3GB'
    #   - -c 'work_mem=5242kB'
    #   - -c 'maintenance_work_mem=256MB'
    #   - -c 'min_wal_size=1GB'
    #   - -c 'max_wal_size=2GB'
    #   - -c 'checkpoint_completion_target=0.7'
    #   - -c 'wal_buffers=16MB'
    #   - -c 'default_statistics_target=100'
    #   - -c 'random_page_cost=4'
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_DIR}/postgres/data:/var/lib/postgresql/data"
      - "${DATA_DIR}/island/scripts/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql"
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
    sysctls:
      - net.core.somaxconn=4096
      # - vm.overcommit_memory=1
    volumes:
      - "${DATA_DIR}/redis:/data"
    labels:
      - "traefik.enable=false"

  # https://www.docker.elastic.co/
  elasticsearch:
    build: elasticsearch
    image: localhost/elasticsearch-oss
    networks:
      - internal
    env_file: .env.elasticsearch
    # sysctls:
    #   - vm.max_map_count=262144 # bug OCI runtime create failed: sysctl "vm.max_map_count" is not in a separate kernel namespace: unknown https://github.com/moby/moby/issues/30778
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
    labels:
      - "traefik.enable=false"

  # solr:
  #   image: solr:7-slim
  #   networks:
  #     - backend
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "${DATA_DIR}/solr:/opt/solr/server/solr/mycores"
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - nextant
  #   labels:
  #     - "traefik.enable=false"

  # adminer:
  #   image: adminer
  #   networks:
  #     - backend
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=8080"
  #     - "traefik.backend=adminer"
  #     - "traefik.network=backend"
  #     - "traefik.frontend.auth.basic=${ADMIN}:${ADMIN_HTPASSWD}"
  #     - "traefik.frontend.rule=Host:adminer.${DOMAIN}"

  # Monitoring 
  cadvisor:
    image: google/cadvisor
    restart: always
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=cadvisor"
      - "traefik.network=backend"
      - "traefik.frontend.auth.basic=${ADMIN}:$$apr1$$ot35v8Up$$0yTQ2LLJqsmPT5SE5W6MF/"
      - "traefik.frontend.rule=Host:cadvisor.${DOMAIN}"

  # Backup
  restic:
    image: lobaro/restic-backup-docker:v1.1
    restart: always
    networks:
      - web
    volumes:
      - "${DATA_DIR}/traefik:/data/traefik"
    env_file:
      - .env.restic
    labels:
      - "traefik.enable=false"

    
