version: "3.7"

networks:
  apps:
    external: true

volumes:
  privatebin-data:

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    networks:
      - apps
    volumes:
      - privatebin-data:/srv/data
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.backend: privatebin
        traefik.port: 8080
        traefik.frontend.rule: Host:privatebin.${DOMAIN},paste.${DOMAIN}
        traefik.frontend.headers.customFrameOptionsValue: "DENY"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.browserXSSFilter: "true"
