version: "3.7"

networks:
  apps:
    external: true

volumes:
  cloudtorrent-data:

services:
  cloudtorrent:
    image: jpillora/cloud-torrent
    networks:
      - apps
    env_file: .env
    volumes:
      - cloudtorrent-data:/downloads
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.backend: cloudtorrent
        traefik.port: 80
        traefik.frontend.rule: Host:torrents.${DOMAIN}
        traefik.frontend.headers.customFrameOptionsValue: "DENY"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.browserXSSFilter: "true"
