version: "3.7"

networks:
  apps:
    external: true

volumes:
  etc:

services:
  traefik:
    image: traefik
    command:
      - --api
      - --api.dashboard
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.onHostRule
      - --acme.email=${ADMIN}@${DOMAIN}
      - --docker
      - --docker.swarmMode
      - --docker.domain=${DOMAIN}
      - --docker.watch
      - --docker.exposedByDefault=false
      - --sendAnonymousUsage=false
      # - --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - etc:/etc/traefik
    networks:
      - app
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.backend: traefik
        traefik.port: 8080
        traefik.frontend.auth.basic.users: ${ADMIN}:$$apr1$$acldxzHL$$aIE2PcUEFioj4PyUvBw/Q.
        traefik.frontend.rule: Host:traefik.${DOMAIN}
        traefik.frontend.headers.customFrameOptionsValue: DENY
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.browserXSSFilter: "true"
