version: "3.7"

networks:
  apps:
    external: true

services:
  glances:
    image: nicolargo/glances:latest-alpine
    pid: host
    networks:
      - apps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GLANCES_OPT: -w
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.backend: glances
        traefik.port: 61208
        traefik.frontend.auth.basic.users: ${ADMIN}:${PASSWORD}
        traefik.frontend.rule: Host:glances.${DOMAIN}
        traefik.frontend.headers.customFrameOptionsValue: "DENY"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.browserXSSFilter: "true"
