version: "3.7"

networks:
  vpn:
    external: true

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    env_file: .env
    networks:
      - vpn
    ports:
      - target: 8009
        published: 8388
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
